### ISSUE TITLE
Circular dependency error when building for docker

### ISSUE THREAD

**Issue by ondrejtomcik** [microsoft/msbuild#1927]
Project created with VS2017 for .net core and with docker support contains docker-compose files in the root folder and Dockerfile in the project folder. It's also standard to have Dockerfile in the root, or in the same folder as docker-compose files.
Problem occurs when Dockerfile is moved next to docker-compose files and context of docker-compose is set to ".".

```
version: '2'
services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: Dockerfile
```
**Output: There is a circular dependency in the target dependency graph involving target "DockerBuildServiceReferences"**.
