### ISSUE TITLE
Manipulating properties with semicolons results in invalid ItemGroup evaluation

### ISSUE THREAD

**Issue by xen2** [Microsoft/msbuild#3940]
### Steps to reproduce

Project file
```xml
<Project>
  <PropertyGroup>
    <TargetFrameworks>a;b</TargetFrameworks>
    <TargetFrameworksTrimmed>$(TargetFrameworks.Trim())</TargetFrameworksTrimmed>
  </PropertyGroup>
  <Target Name="Build">
    <ItemGroup>
      <TargetFramework Include="$(TargetFrameworks)"/>
      <TargetFrameworkTrimmed Include="$(TargetFrameworksTrimmed)"/>
    </ItemGroup>
    <Message Text="TargetFramework: %(TargetFramework.Identity)"/>
    <Message Text="TargetFrameworkTrimmed: %(TargetFrameworkTrimmed.Identity)"/>
  </Target>
</Project>
```

Command line
```
msbuild /bl
```
### Expected  behavior
```
Build:
  TargetFramework: a
  TargetFramework: b
  TargetFrameworkTrimmed: a
  TargetFrameworkTrimmed: b
```

### Actual behavior
```
Build:
  TargetFramework: a
  TargetFramework: b
  TargetFrameworkTrimmed: a;b
```

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856
```
